config/routes.rb
Rails.application.routes.draw do
  get 'orders/paid'
  get 'orders/making'
  get 'orders/shipped'
  get 'orders/completed'
  get 'orders/cancelled'
  
  
  get 'supplier_orders', to: 'supplier_orders#index'
  
  get 'supplier_orders/show'

  get 'supplier_orders/edit'

  get 'supplier_orders/making'
  get 'supplier_orders/shipped'
  get 'supplier_orders/completed'
 
  resources :orders
  root to: 'visitors#index'
  devise_for :users
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  enum status: [:ordered, :paid, :making, :shipped, :completed, :cancelled]
  after_initialize :set_default_status, :if => :new_record?

  def set_default_status
    self.status ||= :ordered
  end
end

app/models/user.rb
class User < ApplicationRecord
  enum role: [:user, :supplier, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
  protect_from_forgery with: :exception
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!
  before_action :admin_only
  before_action :set_order, only: [:show, :paid, :making, :shipped, :completed, :cencelled, :edit, :update, :destroy]

  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.all
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  # POST /orders.json
  def create
    @order = Order.new(order_params)

    respond_to do |format|
      if @order.save
        format.html { redirect_to @order, notice: 'Order was successfully created.' }
        format.json { render :show, status: :created, location: @order }
      else
        format.html { render :new }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    respond_to do |format|
      if @order.update(order_params)
        format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        format.json { render :show, status: :ok, location: @order }
      else
        format.html { render :edit }
        format.json { render json: @order.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @order.destroy
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Order was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def paid
    @order.status = :paid
    @order.save
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Pedido encaminhado para a fábrica!' }
      format.json { head :no_content }
    end
  end
  
  def making
    @order.status = :making
    @order.save
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Pedido em produção' }
      format.json { head :no_content }
    end
  end
  
  def shipped
    @order.status = :shipped
    @order.save
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Pedido enviado!' }
      format.json { head :no_content }
    end
  end
  
  def completed
    @order.status = :completed
    @order.save
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Pedido concluído' }
      format.json { head :no_content }
    end
  end
  
   def cancelled
    @order.status = :cencelled
    @order.save
    respond_to do |format|
      format.html { redirect_to orders_url, notice: 'Pedido cancelado!' }
      format.json { head :no_content }
    end
  end
  
  
  private
  
    def admin_only
      unless current_user.admin?
        redirect_to root_path, :alert => "Acesso negado!"
      end
    end
    
     # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end
   
    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:status, :order_date, :client_name, :email, :phone, :model, :color, :size, :hood_color, :sleeves_color, :embroidery_type, :main_embroidery, :secondary_embroidery, :embroidery_color, :manufactured_date, :delivery_date, :price, :cost_price)
    end
end

app/controllers/supplier_orders_controller.rb
class SupplierOrdersController < ApplicationController
  before_filter :authenticate_user!
  before_action :supplier_only
  before_action :set_order, only: [:show, :paid, :making, :shipped, :completed, :cencelled]
  
  # GET /orders
  # GET /orders.json
  def index
    @orders = Order.where(status:[:paid, :making, :shipped, :cancelled])
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
  end
  
  def making
    @order.status = :making
    @order.save
    respond_to do |format|
      format.html { redirect_to supplier_orders_url, notice: 'Pedido em produção' }
      format.json { head :no_content }
    end
  end
  
  def shipped
    @order.status = :shipped
    @order.save
    respond_to do |format|
      format.html { redirect_to supplier_orders_url, notice: 'Pedido enviado!' }
      format.json { head :no_content }
    end
  end
  
  def completed
    @order.status = :completed
    @order.save
    respond_to do |format|
      format.html { redirect_to supplier_orders_url, notice: 'Pedido concluído' }
      format.json { head :no_content }
    end
  end

  private
  
    def supplier_only
      unless current_user.supplier?
        redirect_to root_path, :alert => "Acesso negado!"
      end
    end
    
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:status, :order_date, :client_name, :email, :phone, :model, :color, :size, :hood_color, :sleeves_color, :embroidery_type, :main_embroidery, :secondary_embroidery, :embroidery_color, :manufactured_date, :delivery_date, :price, :cost_price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to root_path, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to root_path, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/supplier_orders_helper.rb
module SupplierOrdersHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 4.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>" role="alert">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li class='nav-item'><%= link_to 'Configurar conta', edit_user_registration_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Sair', destroy_user_session_path, :method=>'delete', class: 'nav-link' %></li>
<% else %>
  <li class='nav-item'><%= link_to 'Entrar', new_user_session_path, class: 'nav-link' %></li>
  <li class='nav-item'><%= link_to 'Criar Usuário', new_user_registration_path, class: 'nav-link' %></li>
<% end %>
<% if user_signed_in? %>
  <% if current_user.try(:admin?) %>
    <li class='nav-item'><%= link_to 'Editar usuários', users_path, class: 'nav-link' %></li>
    <li class='nav-item'><%= link_to 'Pedidos', orders_path, class: 'nav-link' %></li>
  <% end %>
  <% if current_user.try(:supplier?) %>
    <li class='nav-item'><%= link_to 'Pedidos do fornecedor', supplier_orders_path, class: 'nav-link' %></li>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 4.0 %>
<div class="container">
  <nav class="navbar navbar-light bg-faded">
    <ul class="nav navbar-nav clearfix">
     <nav class="navbar navbar-light bg-faded">
      <a class="navbar-brand" href="#">
       <img src="/assets/Veleta.png" >
        <li class="nav-item">
        <button class="navbar-toggler hidden-sm-up nav-link" type="button" data-toggle="collapse" data-target="#exCollapsingNavbar2" aria-controls="exCollapsingNavbar2" aria-expanded="false" aria-label="Toggle navigation">
                    &#9776;
            </a>
        </button>
      </li>
    </ul>
    <div class="collapse navbar-toggleable-xs" id="exCollapsingNavbar2">
      <%= link_to "Veleta Camisetas", root_path, class: 'navbar-brand' %>
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
        <%= render 'layouts/nav_links_for_auth' %>
      </ul>
    </div>
  </nav>
</div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>
<li class='nav-item'><%= link_to 'Sobre', page_path('about'), class: 'nav-link' %></li>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Rails Devise" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Rails Devise" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => 'reload' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/orders/_form.html.erb
<%= form_for(order) do |f| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :order_date %>
    <%= f.datetime_select :order_date %>
  </div>

  <div class="field">
    <%= f.label :client_name %>
    <%= f.text_field :client_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :phone %>
    <%= f.text_field :phone %>
  </div>

  <div class="field">
    <%= f.label :model %>
    <%= f.number_field :model %>
  </div>

  <div class="field">
    <%= f.label :color %>
    <%= f.text_field :color %>
  </div>

  <div class="field">
    <%= f.label :size %>
    <%= f.number_field :size %>
  </div>

  <div class="field">
    <%= f.label :hood_color %>
    <%= f.text_field :hood_color %>
  </div>

  <div class="field">
    <%= f.label :sleeves_color %>
    <%= f.text_field :sleeves_color %>
  </div>

  <div class="field">
    <%= f.label :embroidery_type %>
    <%= f.number_field :embroidery_type %>
  </div>

  <div class="field">
    <%= f.label :main_embroidery %>
    <%= f.text_field :main_embroidery %>
  </div>

  <div class="field">
    <%= f.label :secondary_embroidery %>
    <%= f.text_field :secondary_embroidery %>
  </div>

  <div class="field">
    <%= f.label :embroidery_color %>
    <%= f.text_field :embroidery_color %>
  </div>

  <div class="field">
    <%= f.label :manufactured_date %>
    <%= f.date_select :manufactured_date %>
  </div>

  <div class="field">
    <%= f.label :delivery_date %>
    <%= f.date_select :delivery_date %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field">
    <%= f.label :cost_price %>
    <%= f.text_field :cost_price %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editar Pedidos</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pedidos</h1>

<table>
  <thead>
    <tr>
      <th>Data do Pedido</th>
      <th>Nome do Cliente</th>
      <th>Email</th>
      <th>telefone</th>
      <th>Modelo</th>
      <th>Cor</th>
      <th>Tamanho</th>
      <th>Status</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.order_date %></td>
        <td><%= order.client_name %></td>
        <td><%= order.email %></td>
        <td><%= order.phone %></td>
        <td><%= order.model %></td>
        <td><%= order.color %></td>
        <td><%= order.size %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Ver', order %></td>
        <td><%= link_to 'Editar', edit_order_path(order) %></td>
        <td><%= link_to 'Excluir', order, method: :delete, data: { confirm: 'Você tem certeza?' } %></td>
        <td class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">status</a>
     <div class="dropdown-menu">
        <a class="dropdown-item" <%= link_to 'Pago', controller: "orders", action: "paid", id:order, data: { confirm: 'PAGAMENTO CONFIRMADO! Deseja encaminhar o pedido para produção?' } %> </a>
        <a class="dropdown-item" <%= link_to 'Em produção', controller: "orders", action: "making", id:order, data: { confirm: 'Moletom em confeccção!' } %> </a>
        <a class="dropdown-item" <%= link_to 'Enviado', controller: "orders", action: "shipped", id:order, data: { confirm: 'Moletom enviado pelo fornecedor!' } %> </a>
       <a class="dropdown-item" <%= link_to 'Concluído', controller: "orders", action: "completed", id:order, data: { confirm: 'Pedido concluído' } %> </a>
       <a class="dropdown-item" <%= link_to 'Cancelado', controller: "orders", action: "cancelled", id:order, data: { confirm: 'Pedido cancelado!' } %> </a>
     
      </td>
     </div> 
 </tr>
      
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Novo pedido', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data do Pedido:</strong>
  <%= @order.order_date %>
</p>

<p>
  <strong>Nome do cliente:</strong>
  <%= @order.client_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @order.phone %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @order.model %>
</p>

<p>
  <strong>Cor:</strong>
  <%= @order.color %>
</p>

<p>
  <strong>Tamanho:</strong>
  <%= @order.size %>
</p>

<p>
  <strong>Cor do capuz:</strong>
  <%= @order.hood_color %>
</p>

<p>
  <strong>Cor das mangas:</strong>
  <%= @order.sleeves_color %>
</p>

<p>
  <strong>Tipo de bordado:</strong>
  <%= @order.embroidery_type %>
</p>

<p>
  <strong>Texto do bordado principal:</strong>
  <%= @order.main_embroidery %>
</p>

<p>
  <strong>Bordado secundário:</strong>
  <%= @order.secondary_embroidery %>
</p>

<p>
  <strong>Cor do bordado:</strong>
  <%= @order.embroidery_color %>
</p>

<p>
  <strong>Data de entrega da fábrica:</strong>
  <%= @order.manufactured_date %>
</p>

<p>
  <strong>Data da entrega:</strong>
  <%= @order.delivery_date %>
</p>

<p>
  <strong>Preço:</strong>
  <%= @order.price %>
</p>

<p>
  <strong>Preço de Custo:</strong>
  <%= @order.cost_price %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> 

app/views/pages/about.html.erb
<% content_for :title do %>About<% end %>
<h3>Sobre a Veleta</h3>
<p>
	Veleta camisetas foi criada em 2015 a fim de atender o mercado de moletons personalizados da Universidade de Brasília
     tendo atingido potencial crescimento no último ano e visando utilizar futuramente apenas ecommerce para atender o mercado de todo o Brasil.
->This web application was created with
<%= link_to('Rails Composer', 'http://railsapps.github.io/rails-composer/') %>
from the <%= link_to('RailsApps project', 'http://railsapps.github.io/') %>.
</p>

app/views/supplier_orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pedidos do Fornecedor</h1>

<table>
  <thead>
    <tr>
      <th>Data do pedido</th>
      <th>Nome do Cliente</th>
      <th>Email</th>
      <th>telefone</th>
      <th>Modelo</th>
      <th>Cor</th>
      <th>Tamanho</th>
      <th>Status</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.order_date %></td>
        <td><%= order.client_name %></td>
        <td><%= order.email %></td>
        <td><%= order.phone %></td>
        <td><%= order.model %></td>
        <td><%= order.color %></td>
        <td><%= order.size %></td>
        <td><%= order.status %></td>
        <td><%= link_to 'Ver', controller: "supplier_orders", action: "show", id:order %></td>
        <td class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">status</a>
     <div class="dropdown-menu">
        
        <a class="dropdown-item" <%= link_to 'Em produção', controller: "supplier_orders", action: "making", id:order, data: { confirm: 'Moletom em confeccção!' } %> </a>
        <a class="dropdown-item" <%= link_to 'Enviado', controller: "supplier_orders", action: "shipped", id:order, data: { confirm: 'Moletom enviado pelo fornecedor!' } %> </a>
       <a class="dropdown-item" <%= link_to 'Concluído', controller: "supplier_orders", action: "completed", id:order, data: { confirm: 'Pedido concluído' } %> </a>
       
     
      </td>
     </div> 
 </tr>
       </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/supplier_orders/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data do Pedido:</strong>
  <%= @order.order_date %>
</p>

<p>
  <strong>Nome do Cliente:</strong>
  <%= @order.client_name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @order.email %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @order.phone %>
</p>

<p>
  <strong>Modelo:</strong>
  <%= @order.model %>
</p>

<p>
  <strong>Cor:</strong>
  <%= @order.color %>
</p>

<p>
  <strong>Tamanho:</strong>
  <%= @order.size %>
</p>

<p>
  <strong>Cor do capuz:</strong>
  <%= @order.hood_color %>
</p>

<p>
  <strong>Cor das mangas:</strong>
  <%= @order.sleeves_color %>
</p>

<p>
  <strong>Tipo de bordado:</strong>
  <%= @order.embroidery_type %>
</p>

<p>
  <strong>Texto do bordado principal:</strong>
  <%= @order.main_embroidery %>
</p>

<p>
  <strong>Bordado secundário:</strong>
  <%= @order.secondary_embroidery %>
</p>

<p>
  <strong>Cor do bordado:</strong>
  <%= @order.embroidery_color %>
</p>

<p>
  <strong>Data de entrega da fábrica:</strong>
  <%= @order.manufactured_date %>
</p>

<p>
  <strong>Data da entrega:</strong>
  <%= @order.delivery_date %>
</p>

<p>
  <strong>Preço:</strong>
  <%= @order.price %>
</p>

<p>
  <strong>Preço de custo:</strong>
  <%= @order.cost_price %>
</p>

<%= link_to 'Edit', edit_order_path(@order) %> |
<%= link_to 'Back', orders_path %>

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Name: <%= @user.name if @user.name %></p>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<h3>Veleta Camisetas</h3>
<p><%= link_to 'Usuários:', users_path %> <%= User.count %> registered</p>